### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MrShadowDev** [DankoOfficial/Loxy-Loxy#10]
Fix it bruh

**Comment by busiawolk** [comment]
Dont copy and paste

**Comment by MrShadowDev** [comment]
I didnt copy and paste i cloned it and run it

**Comment by busiawolk** [comment]
> I didnt copy and paste i cloned it and run it

This is Elon musk

**Comment by DankoOfficial** [comment]
Hey, the whole project is re-written. Enjoy!
