### ISSUE TITLE
Add Intents to the Bot Config

### ISSUE THREAD

**Issue by King-Noob-Show** [DankoOfficial/Loxy-Loxy#20]
_This is my first ever 'issue' so sorry if its bad._

**In [main.py](https://github.com/DankoOfficial/Loxy-Loxy/blob/main/main.py), at Line 1,**

From:
```python
from discord import Activity, ActivityType, Embed
```
Make it:
```python
from discord import Activity, ActivityType, Embed, Intents
```

**AND**

**In [main.py](https://github.com/DankoOfficial/Loxy-Loxy/blob/main/main.py), at Line 16,**

From:
```python
client = commands.Bot(command_prefix=prefix)
``` 
Make it:
```python
client = commands.Bot(command_prefix=prefix, intents=Intents.all())
```

**This makes it so the bot uses the new "[Intents](https://discord.com/developers/docs/topics/gateway#gateway-intents)" system that discord uses and doesn't give an error when starting.**

**Comment by DankoOfficial** [comment]
Okay, thank you so much! Will be updated soon
