### ISSUE TITLE
how do I use it?

### ISSUE THREAD

**Issue by ObeyAmir** [DankoOfficial/Loxy-Loxy#7]
Can someone help me?? I don't understand this, I am new to beaming

**Comment by 09811** [comment]
Add me on dc: akut Game#4299

**Comment by ItsMatrix222** [comment]
cant u tell me here?

**Comment by RealMaMo1086** [comment]
He's

> cant u tell me here?

He's just trying to make you download a password stealer or smh

**Comment by 09811** [comment]
What?


MaMo1086 ***@***.***> schrieb am Do., 9. Feb. 2023, 18:48:

**Comment by Hamder001** [comment]
You can convert to an .exe file if you want or use command prompt but if you dont know how to run a python file is weird !

**Comment by DankoOfficial** [comment]
Hey, the whole project is re-written. Enjoy!

**Comment by ghost** [comment]
> Hey, the whole project is re-written. Enjoy!

Close this issue bro
